// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function DeleteEnvironment(arg1) {
  return window['go']['main']['App']['DeleteEnvironment'](arg1);
}

export function DeleteHistory() {
  return window['go']['main']['App']['DeleteHistory']();
}

export function DeleteHistoryItem(arg1) {
  return window['go']['main']['App']['DeleteHistoryItem'](arg1);
}

export function ExecuteRequest(arg1) {
  return window['go']['main']['App']['ExecuteRequest'](arg1);
}

export function ExportHistory(arg1) {
  return window['go']['main']['App']['ExportHistory'](arg1);
}

export function Generate(arg1, arg2, arg3) {
  return window['go']['main']['App']['Generate'](arg1, arg2, arg3);
}

export function GetAuthInfo(arg1) {
  return window['go']['main']['App']['GetAuthInfo'](arg1);
}

export function GetEnvironments() {
  return window['go']['main']['App']['GetEnvironments']();
}

export function ImportCollections(arg1) {
  return window['go']['main']['App']['ImportCollections'](arg1);
}

export function LoadCollection() {
  return window['go']['main']['App']['LoadCollection']();
}

export function LoadHistory() {
  return window['go']['main']['App']['LoadHistory']();
}

export function ParseSpecDetails(arg1) {
  return window['go']['main']['App']['ParseSpecDetails'](arg1);
}

export function SaveCollection(arg1, arg2) {
  return window['go']['main']['App']['SaveCollection'](arg1, arg2);
}

export function SaveEnvironment(arg1) {
  return window['go']['main']['App']['SaveEnvironment'](arg1);
}

export function SaveHistory(arg1, arg2) {
  return window['go']['main']['App']['SaveHistory'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function UploadFile(arg1) {
  return window['go']['main']['App']['UploadFile'](arg1);
}

export function ValidateSpec(arg1) {
  return window['go']['main']['App']['ValidateSpec'](arg1);
}
