// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pkg} from '../models';
import {generator} from '../models';
import {db} from '../models';
import {frontend} from '../models';

export function DeleteCollection(arg1:string):Promise<void>;

export function DeleteEnvironment(arg1:string):Promise<void>;

export function DeleteHistory():Promise<void>;

export function DeleteHistoryItem(arg1:number):Promise<void>;

export function ExecuteRequest(arg1:pkg.RequestData):Promise<pkg.ResponseData>;

export function ExportCollection(arg1:string,arg2:string):Promise<void>;

export function ExportHistory(arg1:string):Promise<void>;

export function Generate(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetAuthInfo(arg1:string):Promise<Array<generator.AuthScheme>>;

export function GetEnvironments():Promise<Array<db.Environment>>;

export function ImportCollections(arg1:string):Promise<db.PostmanCollection>;

export function LoadCollection():Promise<Array<db.Collection>>;

export function LoadHistory():Promise<Array<db.HistoryRecord>>;

export function ParseSpecDetails(arg1:string):Promise<pkg.SpecDetails>;

export function PerformOAuthFlow(arg1:db.Environment):Promise<db.Environment>;

export function SaveCollection(arg1:string,arg2:Array<pkg.RequestData>):Promise<void>;

export function SaveEnvironment(arg1:db.Environment):Promise<void>;

export function SaveFileDialog(arg1:string,arg2:string,arg3:Array<frontend.FileFilter>):Promise<string>;

export function SaveHistory(arg1:pkg.RequestData,arg2:pkg.ResponseData):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;

export function UploadFile(arg1:string):Promise<Array<number>>;

export function ValidateSpec(arg1:string):Promise<boolean>;
